apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orchestrator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orchestrator-deploy
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Pods
      pods:
        metric:
          name: queue_length
        target:
          type: AverageValue
          averageValue: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30  # Reduced stabilization window for quicker scale down
      policies:
        - type: Pods
          value: 2  # Allow a faster scale down (scale down by 1 pod immediately)
          periodSeconds: 15
        - type: Percent
          value: 50  # This can remain at 100 for aggressive scaling down
          periodSeconds: 15
