apiVersion: v1
kind: ConfigMap # Defines the resource as a ConfigMap
metadata:
  name: prometheus-server-conf # The name of the ConfigMap
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # Global scrape interval: Prometheus will scrape metrics every 15 seconds
    scrape_configs:
      - job_name: 'custom-metric' 
        kubernetes_sd_configs:
          - role: service # Use Kubernetes service discovery (SD) to find services within the cluster
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name] # Label that represents the Kubernetes service name
            action: keep
            regex: orchestrator-metrics # Only keep services where the service name matches 'orchestrator-metrics'